# Header
nav:
  文章: /archives
  关于: /about
  # Categories: /category
  # Tags: /tag

# favicon
favicon: /favicon.png

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/ssssshql
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5

